### ISSUE TITLE
Beta tracker

### ISSUE THREAD

**Issue by jeanlucaslima** [jeanlucaslima/ato#1]
# Manifest 

  - [ ] #2
  - [ ] #3
  - [ ] #4
  - [ ] #5
  - [ ] #6
  - [ ] #7
  - [ ] #8

# Background
- [ ] #9
  - [ ] Track duplicated tabs (by URL)
  - [ ] Create and update background counters  

# UI

- [ ] #10
- [ ] #11
- [ ] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
  - [ ] Show individual tab info: URL, title, if media is playing, if it's duplicated
  - [ ] Close button to close tab
  - [ ] Mute tab
  - [ ] Navigate to tab on click

## Search

- [x] #33
  - [x] #17
  - [x] #18
  - [x] #19
- [x] #20
- [x] #21

# Enhancements 

Those features are not mandatory for a release, but some are appreciated and others are currently not even possible due to lack of Chrome support in released versions. 

- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
